### ISSUE TITLE
Error running This is a simplified example for swinir.

### ISSUE THREAD

**Issue by ukaprch** [theoad/dot-dmax#1]
I created SwinIR.py to run your example using:
model = swinir("classical_sr-4", pretrained=True).to(device)  # <-- replace with any restoration model !

output shows error:

Traceback (most recent call last):
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\modules\Dot-Dmax\SwinIR.py", line 19, in <module>
    dmax.update(x, distribution="target")  # update nat. image statistics
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torchmetrics\metric.py", line 467, in wrapped_func
    raise err
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torchmetrics\metric.py", line 457, in wrapped_func
    update(*args, **kwargs)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\modules\Dot-Dmax\.\dmax\latent_w2.py", line 459, in update
    latents = self.encode(images)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\modules\Dot-Dmax\.\dmax\latent_w2.py", line 422, in encode
    images_normalized = self.normalize(images)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torchvision\transforms\transforms.py", line 277, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torchvision\transforms\functional.py", line 363, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "C:\Users\kaprc\source\repos\CodeProject.AI-Server\src\runtimes\bin\windows\Python38\lib\site-packages\torchvision\transforms\_functional_tensor.py", line 928, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 1, 240, 210] doesn't match the broadcast shape [1, 3, 240, 210]

**Comment by theoad** [comment]
Hi,
Can you give more details about what you are trying to run ? The line `model = swinir("classical_sr-4", pretrained=True).to(device)` refers to the model creation, whereas the error’s call stack starts from line 19: `dmax.update`.

please provide details about your PyTorch version, hardware setup and the type of images on which you’re performing inference. From the error, I guess that the image `x` on which you’re calling `dmax.update` has only one channel (i.e. it is of shape [b, 1, h, w] instead of the expected [b, 3, h, w]).
